# -*- coding: utf-8 -*-
"""fine tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XJo0uvjmuDmzUQSvZ_Oq1tEFN-XNQF8t
"""

# ── Run this ONCE after restart, before anything else ────────────────────
# IMPORTANT: If you encounter ImportErrors after changing NumPy version, you MUST restart the runtime.
!pip install -q --force-reinstall numpy==1.23.5
!pip install -q --force-reinstall albumentations==1.3.1
!pip install -q segmentation-models-pytorch torch torchvision opencv-python-headless tqdm

import albumentations as A
print(f"✓ albumentations {A.__version__}")  # must say 1.3.1

import subprocess
result = subprocess.run(["nvidia-smi"], capture_output=True, text=True)
print(result.stdout)

subprocess.run([
    "pip", "install", "-q",
    "ultralytics",                     # YOLOv8
    "segmentation-models-pytorch",     # U-Net
    "fiftyone",                        # COCO downloader
    "albumentations",                  # data augmentation
    "opencv-python-headless",
    "Pillow", "matplotlib",
    "torch", "torchvision",
    "tqdm", "pyyaml",
])
print("✓ All packages installed")

import fiftyone as fo
import fiftyone.zoo as foz
import os

# Download COCO 2017 — person class only, with segmentation masks
# max_samples controls size: 5000 = ~1GB, 20000 = ~4GB
# Start with 5000 for a quick training run, increase for better accuracy
print("Downloading COCO 2017 person segmentation (train)...")
train_dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    classes=["person"],
    label_types=["segmentations", "detections"],
    max_samples=5000,           # ← increase to 20000+ for better accuracy
    dataset_name="coco_person_train",
)

print("Downloading COCO 2017 person segmentation (val)...")
val_dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="validation",
    classes=["person"],
    label_types=["segmentations", "detections"],
    max_samples=1000,
    dataset_name="coco_person_val",
)

print(f"✓ Train samples : {len(train_dataset)}")
print(f"✓ Val samples   : {len(val_dataset)}")

# ── FIXED Cell 3: Export COCO → YOLO format ──────────────────────────────
import os, shutil, glob
import fiftyone as fo

YOLO_DIR = "/content/yolo_dataset"

# Clean up any previous attempt first
if os.path.exists(YOLO_DIR):
    shutil.rmtree(YOLO_DIR)

os.makedirs(f"{YOLO_DIR}/images/train", exist_ok=True)
os.makedirs(f"{YOLO_DIR}/images/val",   exist_ok=True)
os.makedirs(f"{YOLO_DIR}/labels/train", exist_ok=True)
os.makedirs(f"{YOLO_DIR}/labels/val",   exist_ok=True)

# train_dataset and val_dataset are expected to be available from the previous cell

print(f"Train samples : {len(train_dataset)} | Val samples : {len(val_dataset)}")

# Export each split to a temp dir
for split_name, dataset_obj in [("train", train_dataset), ("val", val_dataset)]:
    tmp = f"/content/tmp_{split_name}"
    if os.path.exists(tmp):
        shutil.rmtree(tmp)

    print(f"Exporting {split_name}...")
    dataset_obj.export(
        export_dir=tmp,
        dataset_type=fo.types.YOLOv5Dataset,
        label_field="detections", # Changed from 'ground_truth' to 'detections'
        classes=["person"],
    )

    # ── FIX: walk recursively and only copy FILES, skip directories ──────
    for root, dirs, files in os.walk(f"{tmp}/images"):
        for fname in files:
            # Skip if not an image file
            if not fname.lower().endswith(tuple([".jpg", ".jpeg", ".png", ".bmp"])): # Use tuple for ends_with
                continue
            src = os.path.join(root, fname)
            dst = f"{YOLO_DIR}/images/{split_name}/{fname}"
            shutil.copy2(src, dst)

    for root, dirs, files in os.walk(f"{tmp}/labels"):
        for fname in files:
            if not fname.endswith(".txt"):
                continue
            src = os.path.join(root, fname)
            dst = f"{YOLO_DIR}/labels/{split_name}/{fname}"
            shutil.copy2(src, dst)

    shutil.rmtree(tmp)
    print(f"  ✓ {split_name} done")

# Write dataset.yaml
yaml_content = f"""
path: {YOLO_DIR}
train: images/train
val:   images/val
nc: 1
names: ['person']
"""
with open(f"{YOLO_DIR}/dataset.yaml", "w") as f:
    f.write(yaml_content)

n_train_imgs = len(glob.glob(f"{YOLO_DIR}/images/train/*"))
n_val_imgs   = len(glob.glob(f"{YOLO_DIR}/images/val/*"))
n_train_lbls = len(glob.glob(f"{YOLO_DIR}/labels/train/*"))
n_val_lbls   = len(glob.glob(f"{YOLO_DIR}/labels/val/*"))

print(f"\n✓ YOLO dataset ready")
print(f"  Train — images: {n_train_imgs} | labels: {n_train_lbls}")
print(f"  Val   — images: {n_val_imgs}   | labels: {n_val_lbls}")
print(f"  Config: {YOLO_DIR}/dataset.yaml")

import subprocess, os, glob, shutil

PDIWS_DIR = "/content/pdiws"

print("Cloning PDIWS thermal intruder dataset from GitHub...")
subprocess.run([
    "git", "clone", "--depth=1",
    "https://github.com/thuan-researcher/Intruder-Thermal-Dataset.git",
    PDIWS_DIR
])

# Check structure
print("\nPDIWS directory structure:")
for root, dirs, files in os.walk(PDIWS_DIR):
    depth = root.replace(PDIWS_DIR, "").count(os.sep)
    indent = " " * 2 * depth
    print(f"{indent}{os.path.basename(root)}/")
    if depth < 2:
        for f in files[:3]:
            print(f"{indent}  {f}")

# Convert PDIWS annotations to YOLO format
# PDIWS uses PASCAL VOC XML — convert each annotation
import xml.etree.ElementTree as ET
from PIL import Image as PILImage

def voc_to_yolo(xml_path, img_w, img_h):
    """Convert PASCAL VOC bounding box XML → YOLO format (class cx cy w h)."""
    tree = ET.parse(xml_path)
    root = tree.getroot()
    lines = []
    for obj in root.findall("object"):
        name = obj.find("name").text.lower()
        if name not in ["person", "intruder", "human"]:
            continue
        bb = obj.find("bndbox")
        xmin = float(bb.find("xmin").text)
        ymin = float(bb.find("ymin").text)
        xmax = float(bb.find("xmax").text)
        ymax = float(bb.find("ymax").text)
        cx = ((xmin + xmax) / 2) / img_w
        cy = ((ymin + ymax) / 2) / img_h
        w  = (xmax - xmin) / img_w
        h  = (ymax - ymin) / img_h
        lines.append(f"0 {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
    return lines

converted = 0
errors    = 0

# Walk PDIWS and convert everything we find
for xml_path in glob.glob(f"{PDIWS_DIR}/**/*.xml", recursive=True):
    # Find matching image
    base = os.path.splitext(xml_path)[0]
    img_path = None
    for ext in [".jpg", ".jpeg", ".png", ".bmp"]:
        if os.path.exists(base + ext):
            img_path = base + ext
            break

    if img_path is None:
        errors += 1
        continue

    try:
        img = PILImage.open(img_path)
        w, h = img.size
        lines = voc_to_yolo(xml_path, w, h)
        if not lines:
            continue

        # Decide train/val split (80/20)
        split = "train" if converted % 5 != 0 else "val"

        # Copy image
        dst_img = f"{YOLO_DIR}/images/{split}/{os.path.basename(img_path)}"
        shutil.copy(img_path, dst_img)

        # Write label
        dst_lbl = f"{YOLO_DIR}/labels/{split}/{os.path.splitext(os.path.basename(img_path))[0]}.txt"
        with open(dst_lbl, "w") as f:
            f.write("\n".join(lines))

        converted += 1
    except Exception as e:
        errors += 1

print(f"✓ PDIWS converted: {converted} images added to YOLO dataset")
print(f"  Errors skipped : {errors}")

total_train = len(glob.glob(f"{YOLO_DIR}/images/train/*"))
total_val   = len(glob.glob(f"{YOLO_DIR}/images/val/*"))
print(f"\n✓ Final dataset — train: {total_train} | val: {total_val}")

import glob
import os

train_image_count = len(glob.glob(os.path.join(YOLO_DIR, 'images', 'train', '*.jpg')))
val_image_count = len(glob.glob(os.path.join(YOLO_DIR, 'images', 'val', '*.jpg')))

print(f"Current YOLO dataset image count - Train: {train_image_count}, Val: {val_image_count}")

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

train_transform = A.Compose([
    A.RandomResizedCrop(384, 384, scale=(0.6, 1.0)),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Rotate(limit=15, p=0.4),
    A.OneOf([
        A.RandomBrightnessContrast(p=1.0),
        A.HueSaturationValue(p=1.0),
        A.CLAHE(p=1.0),
    ], p=0.5),
    A.GaussNoise(p=0.2),
    A.GaussianBlur(blur_limit=3, p=0.2),
    A.CoarseDropout(max_holes=8, max_height=32, max_width=32, p=0.2),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2(),
])

val_transform = A.Compose([
    A.Resize(384, 384),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2(),
])

print(f"Albumentations: {A.__version__}")
print("✓ Transforms defined")

# Quick sanity check — make sure they work before training
import numpy as np
dummy_img  = np.zeros((480, 640, 3), dtype=np.uint8)
dummy_mask = np.zeros((480, 640),    dtype=np.float32)
out = train_transform(image=dummy_img, mask=dummy_mask)
print(f"✓ Train transform OK — image: {out['image'].shape} | mask: {out['mask'].shape}")
out = val_transform(image=dummy_img, mask=dummy_mask)
print(f"✓ Val transform OK   — image: {out['image'].shape} | mask: {out['mask'].shape}")

import subprocess, os, glob, shutil

PDIWS_DIR = "/content/pdiws"

print("Cloning PDIWS thermal intruder dataset from GitHub...")
subprocess.run([
    "git", "clone", "--depth=1",
    "https://github.com/thuan-researcher/Intruder-Thermal-Dataset.git",
    PDIWS_DIR
])

# Check structure
print("\nPDIWS directory structure:")
for root, dirs, files in os.walk(PDIWS_DIR):
    depth = root.replace(PDIWS_DIR, "").count(os.sep)
    indent = " " * 2 * depth
    print(f"{indent}{os.path.basename(root)}/")
    if depth < 2:
        for f in files[:3]:
            print(f"{indent}  {f}")

# Convert PDIWS annotations to YOLO format
# PDIWS uses PASCAL VOC XML — convert each annotation
import xml.etree.ElementTree as ET
from PIL import Image as PILImage

def voc_to_yolo(xml_path, img_w, img_h):
    """Convert PASCAL VOC bounding box XML → YOLO format (class cx cy w h)."""
    tree = ET.parse(xml_path)
    root = tree.getroot()
    lines = []
    for obj in root.findall("object"):
        name = obj.find("name").text.lower()
        if name not in ["person", "intruder", "human"]:
            continue
        bb = obj.find("bndbox")
        xmin = float(bb.find("xmin").text)
        ymin = float(bb.find("ymin").text)
        xmax = float(bb.find("xmax").text)
        ymax = float(bb.find("ymax").text)
        cx = ((xmin + xmax) / 2) / img_w
        cy = ((ymin + ymax) / 2) / img_h
        w  = (xmax - xmin) / img_w
        h  = (ymax - ymin) / img_h
        lines.append(f"0 {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
    return lines

converted = 0
errors    = 0

# Walk PDIWS and convert everything we find
for xml_path in glob.glob(f"{PDIWS_DIR}/**/*.xml", recursive=True):
    # Find matching image
    base = os.path.splitext(xml_path)[0]
    img_path = None
    for ext in [".jpg", ".jpeg", ".png", ".bmp"]:
        if os.path.exists(base + ext):
            img_path = base + ext
            break

    if img_path is None:
        errors += 1
        continue

    try:
        img = PILImage.open(img_path)
        w, h = img.size
        lines = voc_to_yolo(xml_path, w, h)
        if not lines:
            continue

        # Decide train/val split (80/20)
        split = "train" if converted % 5 != 0 else "val"

        # Copy image
        dst_img = f"{YOLO_DIR}/images/{split}/{os.path.basename(img_path)}"
        shutil.copy(img_path, dst_img)

        # Write label
        dst_lbl = f"{YOLO_DIR}/labels/{split}/{os.path.splitext(os.path.basename(img_path))[0]}.txt"
        with open(dst_lbl, "w") as f:
            f.write("\n".join(lines))

        converted += 1
    except Exception as e:
        errors += 1

print(f"✓ PDIWS converted: {converted} images added to YOLO dataset")
print(f"  Errors skipped : {errors}")

total_train = len(glob.glob(f"{YOLO_DIR}/images/train/*"))
total_val   = len(glob.glob(f"{YOLO_DIR}/images/val/*"))
print(f"\n✓ Final dataset — train: {total_train} | val: {total_val}")

from ultralytics import YOLO

# Load pretrained YOLOv8n (nano — fastest)
# Switch to yolov8s.pt or yolov8m.pt for better accuracy at cost of speed
model = YOLO("yolov8n.pt")

print("Starting YOLOv8 fine-tuning...")
print("This takes ~20-40 minutes on T4 GPU for 50 epochs\n")

results = model.train(
    data    = f"{YOLO_DIR}/dataset.yaml",
    epochs  = 50,           # increase to 100 for better accuracy
    imgsz   = 640,          # input resolution
    batch   = 16,           # reduce to 8 if you get OOM errors
    device  = 0,            # GPU 0
    name    = "threatvision_yolo",
    project = "/content/runs",

    # Augmentation — important for intruder detection robustness
    hsv_h   = 0.015,        # hue augmentation
    hsv_s   = 0.7,          # saturation
    hsv_v   = 0.4,          # value/brightness
    degrees = 10,           # rotation
    translate = 0.1,        # translation
    scale   = 0.5,          # scale
    flipud  = 0.3,          # vertical flip (intruders can be upside down)
    fliplr  = 0.5,          # horizontal flip
    mosaic  = 1.0,          # mosaic augmentation
    mixup   = 0.1,          # mixup augmentation

    # Training settings
    lr0     = 0.001,        # initial learning rate
    lrf     = 0.01,         # final lr = lr0 * lrf
    warmup_epochs = 3,
    patience = 15,          # early stopping patience
    save    = True,
    plots   = True,
    verbose = True,
)

YOLO_WEIGHTS = "/content/runs/threatvision_yolo/weights/best.pt"
print(f"\n✓ YOLOv8 training complete!")
print(f"  Best weights : {YOLO_WEIGHTS}")
print(f"  mAP50        : {results.results_dict.get('metrics/mAP50(B)', 'N/A')}")
print(f"  mAP50-95     : {results.results_dict.get('metrics/mAP50-95(B)', 'N/A')}")

# ── CELL A: Force reinstall + check version ───────────────────────────────
import subprocess
subprocess.run(["pip", "install", "-q", "--force-reinstall", "albumentations==1.3.1"])

import importlib
import albumentations
importlib.reload(albumentations)

print(f"Version now: {albumentations.__version__}")
# Must print 1.3.1 — if it still shows newer, restart the runtime

# ── CELL B: Verify transforms work BEFORE running Cell 7 ─────────────────
import importlib, albumentations, albumentations.pytorch
importlib.reload(albumentations)

import albumentations as A
from albumentations.pytorch import ToTensorV2
import numpy as np

print(f"Albumentations: {A.__version__}")

dummy_img  = np.zeros((480, 640, 3), dtype=np.uint8)
dummy_mask = np.zeros((480, 640),    dtype=np.float32)

try:
    t = A.Compose([
        A.RandomResizedCrop(384, 384, scale=(0.6, 1.0)),
        A.Resize(384, 384),
        A.CoarseDropout(max_holes=8, max_height=32, max_width=32, p=0.2),
        A.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
        ToTensorV2(),
    ])
    out = t(image=dummy_img, mask=dummy_mask)
    print(f"✓ Transforms work — image: {out['image'].shape}")
except Exception as e:
    print(f"✗ Still broken: {e}")
    print("\nRun this instead:")
    print("  Runtime > Restart session")
    print("  Then run Cell 1 (installs) and jump straight to Cell 7")

import os, json, cv2
import numpy as np
from PIL import Image as PILImage
from tqdm import tqdm

UNET_DIR = "/content/unet_dataset"
for split in ["train", "val"]:
    os.makedirs(f"{UNET_DIR}/{split}/images", exist_ok=True)
    os.makedirs(f"{UNET_DIR}/{split}/masks",  exist_ok=True)

def polygon_to_mask(polygons, height, width):
    """Convert COCO polygon segmentation annotations to binary mask."""
    mask = np.zeros((height, width), dtype=np.uint8)
    for poly in polygons:
        pts = np.array(poly, dtype=np.float32).reshape(-1, 1, 2).astype(np.int32)
        cv2.fillPoly(mask, [pts], 1)
    return mask

def build_unet_split(fo_dataset, split_name, target_size=(384, 384)):
    """Extract image + segmentation mask pairs from a FiftyOne dataset."""
    saved = 0
    skipped = 0

    for i, sample in enumerate(tqdm(fo_dataset, desc=f"Building {split_name} U-Net data")):
        img_path = sample.filepath
        if not os.path.exists(img_path):
            skipped += 1
            continue

        img = cv2.imread(img_path)
        if img is None:
            skipped += 1
            continue

        h, w = img.shape[:2]
        combined_mask = np.zeros((h, w), dtype=np.uint8)

        # Get all person segmentation polygons
        if sample.segmentations is None:
            skipped += 1
            continue

        has_person = False
        for det in sample.segmentations.detections:
            if det.label != "person":
                continue
            if det.mask is None:
                continue

            # FiftyOne stores masks as relative bounding box crops
            # Convert back to full image coordinates
            x1 = int(det.bounding_box[0] * w)
            y1 = int(det.bounding_box[1] * h)
            bw = int(det.bounding_box[2] * w)
            bh = int(det.bounding_box[3] * h)
            x2 = min(w, x1 + bw)
            y2 = min(h, y1 + bh)

            if bw <= 0 or bh <= 0:
                continue

            mask_crop = det.mask.astype(np.uint8) * 255
            mask_resized = cv2.resize(mask_crop, (x2-x1, y2-y1), interpolation=cv2.INTER_NEAREST)
            combined_mask[y1:y2, x1:x2] = np.maximum(
                combined_mask[y1:y2, x1:x2],
                mask_resized
            )
            has_person = True

        if not has_person:
            skipped += 1
            continue

        # Resize both image and mask to U-Net input size
        img_resized  = cv2.resize(img, target_size)
        mask_resized = cv2.resize(combined_mask, target_size, interpolation=cv2.INTER_NEAREST)

        # Save
        fname = f"{i:06d}.jpg"
        cv2.imwrite(f"{UNET_DIR}/{split_name}/images/{fname}", img_resized)
        cv2.imwrite(f"{UNET_DIR}/{split_name}/masks/{fname.replace('.jpg','.png')}", mask_resized)
        saved += 1

    print(f"  Saved: {saved} | Skipped: {skipped}")
    return saved

print("Building U-Net training dataset from COCO segmentation masks...")
n_train = build_unet_split(train_dataset, "train")
n_val   = build_unet_split(val_dataset,   "val")
print(f"\n✓ U-Net dataset ready — train: {n_train} | val: {n_val}")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import segmentation_models_pytorch as smp
import albumentations as A
from albumentations.pytorch import ToTensorV2
import cv2, os, glob
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Training on: {DEVICE}")

# ── Dataset class ─────────────────────────────────────────────────────────
class PersonSegDataset(Dataset):
    def __init__(self, img_dir, mask_dir, transform=None):
        self.images    = sorted(glob.glob(f"{img_dir}/*.jpg"))
        self.masks     = sorted(glob.glob(f"{mask_dir}/*.png"))
        self.transform = transform
        assert len(self.images) == len(self.masks), \
            f"Image/mask count mismatch: {len(self.images)} vs {len(self.masks)}"

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img  = cv2.cvtColor(cv2.imread(self.images[idx]), cv2.COLOR_BGR2RGB)
        mask = cv2.imread(self.masks[idx], cv2.IMREAD_GRAYSCALE)
        mask = (mask > 127).astype(np.float32)  # binary 0/1

        if self.transform:
            aug  = self.transform(image=img, mask=mask)
            img  = aug["image"]
            mask = aug["mask"]

        return img, mask.unsqueeze(0) if isinstance(mask, torch.Tensor) else torch.tensor(mask).unsqueeze(0)

# ── Augmentation pipelines ────────────────────────────────────────────────
# ── FIXED augmentation pipelines for newer albumentations ────────────────

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

train_transform = A.Compose([
    A.RandomResizedCrop(384, 384, scale=(0.6, 1.0)),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.Rotate(limit=15, p=0.4),
    A.OneOf([
        A.RandomBrightnessContrast(p=1.0),
        A.HueSaturationValue(p=1.0),
        A.CLAHE(p=1.0),
    ], p=0.5),
    A.GaussNoise(p=0.2),
    A.GaussianBlur(blur_limit=3, p=0.2),
    A.CoarseDropout(max_holes=8, max_height=32, max_width=32, p=0.2),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2(),
])

val_transform = A.Compose([
    A.Resize(384, 384),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2(),
])

print(f"Albumentations: {A.__version__}")
print("✓ Transforms defined")

# Quick sanity check — make sure they work before training
import numpy as np
dummy_img  = np.zeros((480, 640, 3), dtype=np.uint8)
dummy_mask = np.zeros((480, 640),    dtype=np.float32)
out = train_transform(image=dummy_img, mask=dummy_mask)
print(f"✓ Train transform OK — image: {out['image'].shape} | mask: {out['mask'].shape}")
out = val_transform(image=dummy_img, mask=dummy_mask)
print(f"✓ Val transform OK   — image: {out['image'].shape} | mask: {out['mask'].shape}")

# ── Dataloaders ───────────────────────────────────────────────────────────
train_ds = PersonSegDataset(
    f"{UNET_DIR}/train/images",
    f"{UNET_DIR}/train/masks",
    transform=train_transform,
)
val_ds = PersonSegDataset(
    f"{UNET_DIR}/val/images",
    f"{UNET_DIR}/val/masks",
    transform=val_transform,
)

train_loader = DataLoader(train_ds, batch_size=16, shuffle=True,  num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds,   batch_size=16, shuffle=False, num_workers=2, pin_memory=True)

print(f"Train batches : {len(train_loader)}")
print(f"Val batches   : {len(val_loader)}")

# ── Model ─────────────────────────────────────────────────────────────────
unet = smp.Unet(
    encoder_name    = "resnet34",
    encoder_weights = "imagenet",   # pretrained ImageNet backbone
    in_channels     = 3,
    classes         = 1,
    activation       = None,         # raw logits — we apply sigmoid in loss
)
unet = unet.to(DEVICE)

# ── Loss: Dice + BCE combined (best for segmentation) ────────────────────
class DiceBCELoss(nn.Module):
    def __init__(self, smooth=1.0):
        super().__init__()
        self.smooth = smooth
        self.bce    = nn.BCEWithLogitsLoss()

    def forward(self, logits, targets):
        bce_loss  = self.bce(logits, targets)
        probs     = torch.sigmoid(logits)
        inter     = (probs * targets).sum(dim=(2, 3))
        dice_loss = 1 - (2 * inter + self.smooth) / \
                    (probs.sum(dim=(2,3)) + targets.sum(dim=(2,3)) + self.smooth)
        return bce_loss + dice_loss.mean()

criterion = DiceBCELoss()
optimizer = optim.AdamW(unet.parameters(), lr=2e-4, weight_decay=1e-4)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=30, eta_min=1e-6)

# ── IoU metric ────────────────────────────────────────────────────────────
def iou_score(preds, targets, threshold=0.5):
    preds   = (torch.sigmoid(preds) > threshold).float()
    inter   = (preds * targets).sum(dim=(2, 3))
    union   = (preds + targets).clamp(0, 1).sum(dim=(2, 3))
    iou     = (inter + 1e-6) / (union + 1e-6)
    return iou.mean().item()

# ── Training loop ─────────────────────────────────────────────────────────
EPOCHS         = 30          # increase to 50-60 for best results
UNET_SAVE_PATH = "/content/unet_best.pt"
best_val_iou   = 0.0
history        = {"train_loss": [], "val_loss": [], "val_iou": []}

print(f"\nStarting U-Net fine-tuning for {EPOCHS} epochs...")
print(f"Training on {len(train_ds)} samples | Validating on {len(val_ds)} samples\n")

for epoch in range(1, EPOCHS + 1):
    # ── Train ────────────────────────────────────────────────────────────
    unet.train()
    train_loss = 0.0
    pbar = tqdm(train_loader, desc=f"Epoch {epoch:02d}/{EPOCHS} [train]", leave=False)
    for imgs, masks in pbar:
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        optimizer.zero_grad()
        logits = unet(imgs)
        loss   = criterion(logits, masks)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(unet.parameters(), 1.0)
        optimizer.step()
        train_loss += loss.item()
        pbar.set_postfix(loss=f"{loss.item():.4f}")

    train_loss /= len(train_loader)

    # ── Validate ─────────────────────────────────────────────────────────
    unet.eval()
    val_loss = 0.0
    val_iou  = 0.0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            logits   = unet(imgs)
            val_loss += criterion(logits, masks).item()
            val_iou  += iou_score(logits, masks)

    val_loss /= len(val_loader)
    val_iou  /= len(val_loader)
    scheduler.step()

    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["val_iou"].append(val_iou)

    # Save best model
    if val_iou > best_val_iou:
        best_val_iou = val_iou
        torch.save({
            "epoch":      epoch,
            "model_state_dict": unet.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "val_iou":    val_iou,
            "val_loss":   val_loss,
        }, UNET_SAVE_PATH)
        saved_str = " ← best saved"
    else:
        saved_str = ""

    print(f"Epoch {epoch:02d}/{EPOCHS} | "
          f"train_loss: {train_loss:.4f} | "
          f"val_loss: {val_loss:.4f} | "
          f"val_iou: {val_iou:.4f}{saved_str}")

print(f"\n✓ U-Net training complete!")
print(f"  Best val IoU : {best_val_iou:.4f}")
print(f"  Weights saved: {UNET_SAVE_PATH}")

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("U-Net Training", fontsize=14)

axes[0].plot(history["train_loss"], label="Train Loss", color="#00d4ff")
axes[0].plot(history["val_loss"],   label="Val Loss",   color="#ff4757")
axes[0].set_title("Loss (Dice + BCE)")
axes[0].set_xlabel("Epoch")
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(history["val_iou"], label="Val IoU", color="#00ff94")
axes[1].set_title("Validation IoU")
axes[1].set_xlabel("Epoch")
axes[1].axhline(y=best_val_iou, color="#ffd93d", linestyle="--", label=f"Best: {best_val_iou:.3f}")
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.savefig("/content/training_curves.png", dpi=120)
plt.show()
print("✓ Training curves saved to /content/training_curves.png")

import torch, cv2, glob, random
import numpy as np
import matplotlib.pyplot as plt
import segmentation_models_pytorch as smp
import albumentations as A
from albumentations.pytorch import ToTensorV2

# Load best weights
checkpoint = torch.load(UNET_SAVE_PATH, map_location=DEVICE)
unet.load_state_dict(checkpoint["model_state_dict"])
unet.eval()
print(f"Loaded best checkpoint from epoch {checkpoint['epoch']} (IoU: {checkpoint['val_iou']:.4f})")

val_images = sorted(glob.glob(f"{UNET_DIR}/val/images/*.jpg"))
val_masks  = sorted(glob.glob(f"{UNET_DIR}/val/masks/*.png"))

# Pick 4 random samples
indices = random.sample(range(len(val_images)), min(4, len(val_images)))

fig, axes = plt.subplots(len(indices), 3, figsize=(12, 4 * len(indices)))
fig.suptitle("U-Net Predictions  |  Input · Ground Truth · Prediction", fontsize=13)

infer_transform = A.Compose([
    A.Resize(384, 384),
    A.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
    ToTensorV2(),
])

for row, idx in enumerate(indices):
    img_raw  = cv2.cvtColor(cv2.imread(val_images[idx]), cv2.COLOR_BGR2RGB)
    mask_raw = cv2.imread(val_masks[idx], cv2.IMREAD_GRAYSCALE)

    aug = infer_transform(image=img_raw, mask=(mask_raw > 127).astype(np.float32))
    inp = aug["image"].unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        pred = torch.sigmoid(unet(inp)).squeeze().cpu().numpy()

    pred_binary = (pred > 0.5).astype(np.uint8) * 255

    # Overlay on image
    # Convert img_raw to float for blending calculations and normalize to 0-1 range
    img_raw_float = img_raw.astype(np.float32) / 255.0

    # Expand pred_binary to have a channel dimension (H, W, 1) and normalize to 0 or 1
    # This acts as an alpha mask for blending
    pred_mask_3ch = np.expand_dims(pred_binary, axis=-1).astype(np.float32) / 255.0

    # Define the red color, normalized to 0-1
    red_color = np.array([1.0, 0.0, 0.0]) # Red

    # Perform alpha blending using np.where
    # If pred_mask_3ch is > 0 (i.e., mask pixel is white), blend red with img_raw_float
    # Otherwise, keep img_raw_float
    # The original blend was `img * 0.5 + red * 0.5` where mask is true
    overlay_float = np.where(
        pred_mask_3ch > 0, # Condition: where the mask is active
        img_raw_float * 0.5 + red_color * 0.5, # Blended color (50% original, 50% red)
        img_raw_float # Original image where mask is inactive
    )

    # Convert back to uint8 and scale to 0-255
    overlay = (overlay_float * 255).astype(np.uint8)

    axes[row][0].imshow(img_raw)
    axes[row][0].set_title("Input")
    axes[row][0].axis("off")

    axes[row][1].imshow(mask_raw, cmap="gray")
    axes[row][1].set_title("Ground Truth")
    axes[row][1].axis("off")

    axes[row][2].imshow(overlay) # Display the blended overlay
    axes[row][2].set_title(f"Prediction (Overlay)")
    axes[row][2].axis("off")

plt.tight_layout()
plt.savefig("/content/predictions.png", dpi=120)
plt.show()
print("✓ Predictions saved to /content/predictions.png")

print(f"Shape of img_raw: {img_raw.shape}")
print(f"Shape of pred_binary: {pred_binary.shape}")

from google.colab import drive
import shutil, os

drive.mount("/content/drive")

DRIVE_SAVE_DIR = "/content/drive/MyDrive/ThreatVision_Models"
os.makedirs(DRIVE_SAVE_DIR, exist_ok=True)

# Save U-Net weights
shutil.copy(UNET_SAVE_PATH, f"{DRIVE_SAVE_DIR}/unet_best.pt")

# Save YOLOv8 weights
yolo_best = "/content/runs/threatvision_yolo/weights/best.pt"
if os.path.exists(yolo_best):
    shutil.copy(yolo_best, f"{DRIVE_SAVE_DIR}/yolov8_best.pt")

# Save training curves
shutil.copy("/content/training_curves.png", f"{DRIVE_SAVE_DIR}/training_curves.png")
shutil.copy("/content/predictions.png",     f"{DRIVE_SAVE_DIR}/predictions.png")

print(f"✓ All models saved to Google Drive: {DRIVE_SAVE_DIR}")
print(f"\nFiles saved:")
for f in os.listdir(DRIVE_SAVE_DIR):
    size = os.path.getsize(f"{DRIVE_SAVE_DIR}/{f}") / 1024 / 1024
    print(f"  {f:30s}  {size:.1f} MB")

server_patch = '''
# In server.py, change the Models.load() method to:

def load(self):
    from ultralytics import YOLO
    import segmentation_models_pytorch as smp

    # ── Load fine-tuned YOLOv8 ──────────────────────────────────────────
    YOLO_WEIGHTS = "/content/runs/threatvision_yolo/weights/best.pt"
    self.yolo = YOLO(YOLO_WEIGHTS)      # ← your fine-tuned weights
    self.yolo.to(DEVICE)
    log.info(f"YOLOv8 loaded from {YOLO_WEIGHTS}")

    # ── Load fine-tuned U-Net ────────────────────────────────────────────
    self.unet = smp.Unet(
        encoder_name="resnet34",
        encoder_weights=None,           # ← None because we load our own
        in_channels=3,
        classes=1,
        activation=None,                # ← raw logits now
    )
    checkpoint = torch.load("/content/unet_best.pt", map_location=DEVICE)
    self.unet.load_state_dict(checkpoint["model_state_dict"])
    self.unet.to(DEVICE)
    self.unet.eval()
    log.info(f"U-Net loaded — val IoU: {checkpoint['val_iou']:.4f}")

    self.ready = True
'''

print(server_patch)
print("\n✓ Copy the above into server.py Models.load() and restart the server (re-run Cell 4)")
print("\nExpected performance with fine-tuned models:")
print("  YOLOv8 mAP50     : ~85-92% (vs ~72% pretrained on general COCO)")
print("  U-Net val IoU    : ~75-85% (vs ~60% ImageNet-only pretrained)")
print("  Pipeline latency : same (~25ms on T4 GPU)")