# -*- coding: utf-8 -*-
"""U-net video clearing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2JHYEN-JeaMRpXYLyxXmCyA-7gw98By
"""

!nvidia-smi

from pyngrok import ngrok
import time

# Kill any old tunnels
ngrok.kill()
time.sleep(2)

# Open fresh tunnel
tunnel = ngrok.connect(8000, "http")
PUBLIC_URL = tunnel.public_url

print("=" * 50)
print(f"NEW URL : {PUBLIC_URL}")
print(f"Health  : {PUBLIC_URL}/health")
print(f"WS URL  : {PUBLIC_URL.replace('https','wss').replace('http','ws')}/stream")
print("=" * 50)

# Verify it works
import requests
time.sleep(2)
try:
    r = requests.get(f"{PUBLIC_URL}/health", timeout=5).json()
    print(f"\n✓ Tunnel working — server status: {r['status']}")
except Exception as e:
    print(f"\n✗ Still not working: {e}")

# ── Kill ngrok completely ─────────────────────────────────────────────────
from pyngrok import ngrok
ngrok.kill()

# ── Install localtunnel ───────────────────────────────────────────────────
import subprocess
subprocess.run(["npm", "install", "-g", "localtunnel"], capture_output=True)

# ── Start localtunnel in background ──────────────────────────────────────
import threading, time

tunnel_url = {"url": None}

def run_tunnel():
    result = subprocess.run(
        ["lt", "--port", "8000", "--subdomain", "threatvision-gpu"],
        capture_output=True, text=True
    )
    print(result.stdout)
    print(result.stderr)

t = threading.Thread(target=run_tunnel, daemon=True)
t.start()
time.sleep(4)

# ── Get the URL ───────────────────────────────────────────────────────────
print("=" * 50)
print("URL : https://threatvision-gpu.loca.lt")
print("WS  : wss://threatvision-gpu.loca.lt/stream")
print("=" * 50)

# ── Verify ────────────────────────────────────────────────────────────────
import requests, time
for i in range(10):
    try:
        r = requests.get(
            "https://threatvision-gpu.loca.lt/health",
            headers={"bypass-tunnel-reminder": "true"},
            timeout=5
        ).json()
        print(f"✓ Working — status: {r['status']}")
        break
    except Exception as e:
        print(f"  Waiting... ({e})")
        time.sleep(3)

# Check localtunnel password
import requests
ip = requests.get("https://api.ipify.org").text
print(f"Your IP (localtunnel password): {ip}")
print(f"\nOpen this in browser and enter the IP above as password:")
print(f"https://threatvision-gpu.loca.lt")

!pip install -q fastapi uvicorn[standard] pyngrok \
    ultralytics segmentation-models-pytorch \
    opencv-python-headless Pillow nest_asyncio

server_code = '''
import asyncio, base64, json, logging, time, uuid
from collections import deque
from datetime import datetime
from typing import Optional

# ── Add this to server.py — replace the run_pipeline function ─────────────

import cv2
import numpy as np

def sharpen_region(img):
    """Apply unsharp mask to make region ultra crisp."""
    gaussian = cv2.GaussianBlur(img, (0, 0), 3)
    sharpened = cv2.addWeighted(img, 2.5, gaussian, -1.5, 0)
    return sharpened

def run_pipeline(frame_bgr: np.ndarray) -> dict:
    import time, uuid
    from datetime import datetime

    t_start = time.perf_counter()
    h, w = frame_bgr.shape[:2]
    output = frame_bgr.copy()
    threats = []

    # ── Step 1: YOLO detection ────────────────────────────────────────────
    results = models.yolo(
        frame_bgr,
        conf=YOLO_CONF_THRESHOLD,
        iou=YOLO_IOU_THRESHOLD,
        classes=list(THREAT_CLASSES.keys()),
        verbose=False,
        device=DEVICE,
    )

    detections = []
    if results and len(results[0].boxes):
        for box in results[0].boxes:
            cls_id = int(box.cls.item())
            conf   = float(box.conf.item())
            xyxy   = box.xyxy[0].tolist()
            if cls_id in THREAT_CLASSES:
                detections.append({
                    "class": THREAT_CLASSES[cls_id],
                    "confidence": round(conf, 3),
                    "box": [round(v) for v in xyxy],
                })

    threat_detected = len(detections) > 0

    if threat_detected:
        # ── Step 2: Build combined U-Net mask for ALL detections ──────────
        full_mask = np.zeros((h, w), dtype=np.uint8)

        with torch.no_grad():
            for det in detections:
                box = det["box"]
                tensor, (x1, y1, x2, y2) = preprocess_for_unet(frame_bgr, box)
                if tensor is None:
                    continue

                mask_out = models.unet(tensor)
                mask_np  = postprocess_mask(mask_out, (x2 - x1, y2 - y1))
                full_mask[y1:y2, x1:x2] = np.maximum(
                    full_mask[y1:y2, x1:x2], mask_np
                )

                threats.append({
                    "class": det["class"],
                    "confidence": det["confidence"],
                    "box": det["box"],
                })

        # ── Step 3: Blur entire frame first ───────────────────────────────
        # Heavy blur on background (non-threat areas)
        blurred_bg = cv2.GaussianBlur(frame_bgr, (31, 31), 0)

        # ── Step 4: Sharpen the threat region ─────────────────────────────
        sharpened = sharpen_region(frame_bgr)

        # ── Step 5: Compose — sharp threat on blurred background ──────────
        mask_3ch = cv2.cvtColor(full_mask, cv2.COLOR_GRAY2BGR)
        mask_norm = mask_3ch.astype(np.float32) / 255.0

        # Hard edge — instant clear, no fade
        mask_binary = (mask_norm > 0.5).astype(np.float32)

        output = (sharpened * mask_binary + blurred_bg * (1 - mask_binary)).astype(np.uint8)

        # ── Step 6: Red outline contour around threat ─────────────────────
        contours, _ = cv2.findContours(full_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        cv2.drawContours(output, contours, -1, (0, 0, 255), 3)

        # ── Step 7: Bounding box + label for each detection ───────────────
        for det in detections:
            bx1, by1, bx2, by2 = det["box"]
            cv2.rectangle(output, (bx1, by1), (bx2, by2), (0, 0, 220), 2)
            label = f"INTRUDER {det['confidence']*100:.0f}%"
            lw, lh = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)[0]
            cv2.rectangle(output, (bx1, by1 - lh - 10), (bx1 + lw + 8, by1), (0, 0, 200), -1)
            cv2.putText(output, label, (bx1 + 4, by1 - 6),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

    # ── Step 8: Status badge ──────────────────────────────────────────────
    status_color = (0, 0, 200) if threat_detected else (0, 180, 0)
    status_text  = f"THREAT ({len(threats)}) — REGION CLEARED" if threat_detected else "CLEAR"
    elapsed_ms   = (time.perf_counter() - t_start) * 1000
    ts = datetime.utcnow().strftime("%H:%M:%S UTC")

    cv2.rectangle(output, (0, 0), (w, 36), (0, 0, 0), -1)
    cv2.rectangle(output, (0, 0), (w, 36), status_color, 2)
    cv2.putText(output, f"ThreatVision  |  {status_text}  |  {ts}  |  {elapsed_ms:.1f}ms",
                (10, 24), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 1)

    # ── Alert log ─────────────────────────────────────────────────────────
    if threat_detected:
        alert_history.append({
            "id": str(uuid.uuid4())[:8],
            "timestamp": datetime.utcnow().isoformat(),
            "threat_count": len(threats),
            "threats": threats,
            "pipeline_ms": round(elapsed_ms, 1),
        })
        log.warning(f"THREAT: {len(threats)} intruder(s) | region cleared | {elapsed_ms:.1f}ms")

    return {
        "annotated_frame": output,
        "threat_detected": threat_detected,
        "threat_count": len(threats),
        "threats": threats,
        "pipeline_ms": round(elapsed_ms, 1),
    }
'''

!pip install pyngrok -q
import nest_asyncio
import uvicorn
import threading
from pyngrok import ngrok, conf

nest_asyncio.apply()

import nest_asyncio
import uvicorn
import threading
import time
from pyngrok import ngrok
from google.colab import userdata # Import userdata to get secrets

nest_asyncio.apply()

# Correctly retrieve NGROK_TOKEN from Colab secrets
NGROK_TOKEN = userdata.get('NGROK_TOKEN')
ngrok.set_auth_token(NGROK_TOKEN)
ngrok.kill()

# ── Start uvicorn FIRST ───────────────────────────────────────────────────
def run():
    # Ensure current directory is in path for 'server.py'
    import sys
    sys.path.append('.')

    # Re-install ultralytics and segmentation_models_pytorch in this specific context
    # to ensure they are available for the server
    try:
        import ultralytics
    except ModuleNotFoundError:
        print("Installing ultralytics in server thread...")
        import subprocess
        subprocess.run([sys.executable, "-m", "pip", "install", "ultralytics", "-q"], capture_output=True)
        print("ultralytics installed in server thread.")

    try:
        import segmentation_models_pytorch as smp
    except ModuleNotFoundError:
        print("Installing segmentation_models_pytorch in server thread...")
        import subprocess
        subprocess.run([sys.executable, "-m", "pip", "install", "segmentation_models_pytorch", "-q"], capture_output=True)
        print("segmentation_models_pytorch installed in server thread.")

    uvicorn.run("server:app", host="0.0.0.0", port=8000, log_level="info")

t = threading.Thread(target=run, daemon=True)
t.start()

# ── Wait for server to actually be up ────────────────────────────────────
print("Waiting for server to start...")
import socket
for i in range(30):
    try:
        s = socket.create_connection(("localhost", 8000), timeout=1)
        s.close()
        print(f"✓ Server is up (took {i+1}s)")
        break
    except:
        time.sleep(1)
        print(f"  {i+1}s...")
else:
    print("✗ Server didn't start after 30s — check for errors above")

# ── THEN open ngrok tunnel ────────────────────────────────────────────────
tunnel = ngrok.connect(8000, "http")
PUBLIC_URL = tunnel.public_url

print("=" * 60)
print(f"  PUBLIC API URL : {PUBLIC_URL}")
print(f"  Swagger docs   : {PUBLIC_URL}/docs")
print(f"  Health check   : {PUBLIC_URL}/health")
print(f"  WebSocket      : {PUBLIC_URL.replace('https','wss').replace('http','ws')}/stream")
print("=" * 60)

# ── Wait for models to load (takes ~30s on first run) ────────────────────
import requests
print("\nWaiting for models to load...")
for i in range(24):
    try:
        r = requests.get(f"{PUBLIC_URL}/health", timeout=5).json()
        status = r.get("status")
        device = r.get("device", "?")
        print(f"  {i*5}s — status: {status} | device: {device}")
        if status == "ready":
            print("✓ All models loaded and ready!")
            break
    except Exception as e:
        print(f"  {i*5}s — not ready yet ({e})")
    time.sleep(5)

import requests, base64, cv2
from IPython.display import display, Image as IPImage
import numpy as np

# Download a test image (public domain crowd photo)
test_url = "https://raw.githubusercontent.com/ultralytics/yolov5/master/data/images/zidane.jpg"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"}
img_data = requests.get(test_url, headers=headers).content

# Wait for models to be ready
import time
for i in range(12):
    r = requests.get(f"{PUBLIC_URL}/health").json()
    print(f"Server status: {r['status']} | device: {r.get('device','?')}")
    if r["status"] == "ready":
        print("✓ Models loaded!")
        break
    time.sleep(5)

# Encode and send
b64 = "data:image/jpeg;base64," + base64.b64encode(img_data).decode()
resp = requests.post(f"{PUBLIC_URL}/analyze", json={"frame": b64, "camera_id": "colab-test"})
result = resp.json()

print(f"\nThreat detected : {result['threat_detected']}")
print(f"Threat count    : {result['threat_count']}")
print(f"Pipeline time   : {result['pipeline_ms']}ms")
print(f"Threats         : {result['threats']}")

# Display annotated frame
raw = base64.b64decode(result["annotated_frame"].split(",")[1])
arr = np.frombuffer(raw, np.uint8)
frame = cv2.imdecode(arr, cv2.IMREAD_COLOR)
frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

from PIL import Image
import io
buf = io.BytesIO()
Image.fromarray(frame_rgb).save(buf, format="JPEG")
display(IPImage(data=buf.getvalue()))

import requests

r = requests.get(f"{PUBLIC_URL}/health").json()
print(r)

def load(self):
    from ultralytics import YOLO
    import segmentation_models_pytorch as smp

    # Mount Drive first
    from google.colab import drive
    drive.mount("/content/drive")
    DRIVE_DIR = "/content/drive/MyDrive/ThreatVision_Models"

    # Fine-tuned YOLOv8
    self.yolo = YOLO(f"{DRIVE_DIR}/yolov8_best.pt")
    self.yolo.to(DEVICE)
    log.info("✓ Fine-tuned YOLOv8 loaded")

    # Fine-tuned U-Net
    self.unet = smp.Unet(
        encoder_name="resnet34",
        encoder_weights=None,   # no imagenet — loading our own weights
        in_channels=3,
        classes=1,
        activation=None,
    )
    checkpoint = torch.load(f"{DRIVE_DIR}/unet_best.pt", map_location=DEVICE)
    self.unet.load_state_dict(checkpoint["model_state_dict"])
    self.unet.to(DEVICE)
    self.unet.eval()
    log.info(f"✓ Fine-tuned U-Net loaded — val IoU: {checkpoint['val_iou']:.4f}")

    self.ready = True

import requests

# URL for a sample image from the COCO dataset (or a similar source) showing people
sample_coco_image_url = "http://images.cocodataset.org/val2017/000000039769.jpg"

# Define headers to mimic a browser request
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"}

# Download the image
response = requests.get(sample_coco_image_url, headers=headers)

# Save the image to a file
image_filename = "sample_person_image.jpg"
with open(image_filename, "wb") as f:
    f.write(response.content)

print(f"Downloaded '{image_filename}' to your Colab environment.")
print(f"You can now upload this file using the 'Choose Files' button in the cell above.")

import requests, json

try:
    resp = requests.get(f"{PUBLIC_URL}/alerts")
    resp.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)
    alerts = resp.json()
    print(f"Total alerts logged: {alerts['total']}\n")
    for a in alerts["alerts"]:
        print(f"[{a['timestamp']}] {a['threat_count']} threat(s) | {a['pipeline_ms']}ms | id: {a['id']}")
except requests.exceptions.RequestException as e:
    print(f"Error fetching alerts: {e}")
    if hasattr(e, 'response') and e.response is not None:
        print(f"Server response status code: {e.response.status_code}")
        print(f"Server response content: {e.response.text}")
except json.JSONDecodeError as e:
    print(f"Error decoding JSON from server: {e}")
    # If resp was defined before the .json() call, print its text content
    if 'resp' in locals() and resp is not None:
        print(f"Raw server response: {resp.text}")
    else:
        print("No response object available to inspect.")

print("""
To connect your React dashboard to this Colab server:

1. Open Dashboard.jsx
2. Change the top two lines to:

   const API_BASE = "{public_url}";
   const WS_URL   = "{ws_url}/stream";

3. Save and refresh your React app.
   It will connect to this Colab server in real time.

Note: The URL changes every time you restart Colab.
For a permanent URL, deploy to Railway or Cloud Run instead.
""".format(
    public_url=PUBLIC_URL,
    ws_url=PUBLIC_URL.replace("https","wss").replace("http","ws")
))

# Paste in any empty cell in Notebook 1 — keeps session alive
import time
while True:
    time.sleep(30)
    print(".", end="", flush=True)